# config/agents_config.yaml
langchain_config:
  llm:
    provider: "ollama" 
    model: "llama3.2:latest"
    temperature: 0.1
    max_tokens: 1000
  
  # Embedding model for vector stores
  embeddings:
    provider: "ollama"  
    model: "mxbai-embed-large"  
  
  # Vector store configuration
  vector_stores:
    pizza_descriptions:
      type: "chroma" 
      persist_directory: "data/vector_stores/pizza_descriptions"
      collection_name: "pizzas"
    
    allergen_data:
      type: "chroma"
      persist_directory: "data/vector_stores/allergen_data" 
      collection_name: "allergens"
    
    recipes:
      type: "chroma"
      persist_directory: "data/vector_stores/recipes"
      collection_name: "recipes"
    
    nutrition_data:
      type: "chroma"
      persist_directory: "data/vector_stores/nutrition"
      collection_name: "nutrition"
  
  agent_executor:
    type: "react"  # or "react", "structured_chat"
    max_iterations: 5
    early_stopping_method: "generate"
    verbose: true

tools:
  pizza_search:
    name: "pizza_search"
    description: "Search for pizza information, prices, and descriptions"
    vector_store: "pizza_descriptions"
    retriever_type: "similarity"
    k: 5
    
  allergen_check:
    name: "allergen_safety_check"
    description: "Check allergen information for pizzas - CRITICAL for customer safety"
    vector_store: "allergen_data"
    retriever_type: "mmr"  # Maximum marginal relevance for safety
    k: 3
    safety_mode: true
    confidence_threshold: 0.99
    
  ingredient_lookup:
    name: "ingredient_lookup"
    description: "Get detailed ingredient lists and preparation information"
    vector_store: "recipes"
    retriever_type: "similarity"
    k: 4
    
  nutrition_info:
    name: "nutrition_information"
    description: "Retrieve nutritional information and calorie data"
    vector_store: "nutrition_data"
    retriever_type: "similarity"
    k: 3

# Rest of config...
agent_prompts:
  system_prompt: |
    You are a helpful assistant for Pizzeria Bella Napoli. You help customers with:
    - Pizza menu information and prices
    - Ingredient lists and allergen information (CRITICAL - always double-check allergen data)
    - Nutritional information
    - General questions about our pizzas
    
    SAFETY RULES:
    - For allergen queries, ALWAYS use the allergen_safety_check tool
    - If allergen information confidence is below 99%, ask customer to contact restaurant directly
    - Be precise and helpful with ingredient information
    - Always cite your sources when providing factual information
    
  human_prompt: |
    Customer question: {input}
    
    Previous conversation: {chat_history}
    
    Available tools: {tools}
    
    Please provide a helpful, accurate response. For allergen questions, prioritize safety.

memory:
  type: "conversation_buffer_window"
  k: 10  # Remember last 10 exchanges
  return_messages: true

routing:
  strategy: "similarity_based"  # LangChain handles routing via tool descriptions
  fallback_tool: "pizza_search"