# config/extraction_config.yaml

# Document Processing Configuration
document_processing:
  # Supported file formats
  supported_formats: [".pdf", ".txt", ".docx"]
  
  # Output directories
  output_paths:
    extracted_text: "docs/processed/extracted_text"
    structured_data: "docs/processed/structured_data"
    embeddings: "docs/processed/embeddings"
    validation: "docs/validation"
  
  # Quality thresholds
  quality_thresholds:
    min_extraction_confidence: 0.8
    min_text_density: 0.1
    min_language_coherence: 0.7
    allergen_safety_threshold: 0.99

# PDF Extraction Pipeline
pdf_extraction:
  # Extraction strategy priority order
  extraction_methods:
    - name: "pdfplumber"
      priority: 1
      use_for: ["tables", "structured_text"]
      
    - name: "pymupdf"
      priority: 2
      use_for: ["text", "images", "layout"]
      
    - name: "tesseract_ocr"
      priority: 3
      use_for: ["scanned_pdfs", "image_text"]
      
    - name: "easyocr"
      priority: 4
      use_for: ["fallback_ocr", "multilingual"]

  # Document type detection
  document_classification:
    menu_catalog:
      keywords: ["pizza", "menu", "carte", "prix", "€", "margherita", "quattro", "napoletana", "fromage", "tomate"]
      patterns: ["pizza\\s+\\w+", "\\d+[.,]\\d{2}\\s*€", "menu|carte"]
      
    allergen_table:
      keywords: ["allergen", "allergène", "gluten", "lactose", "oeuf", "arachide", "noix", "soja", "celeri", "moutarde"]
      patterns: ["allergen|allergène", "gluten|lactose", "tableau.*allergen"]
      
    recipe:
      keywords: ["recette", "ingrédients", "preparation", "étapes", "cuisson", "temps", "portions"]
      patterns: ["recette\\s+\\w+", "ingrédients?\\s*:", "préparation|preparation", "\\d+\\s*min"]
      
    nutrition:
      keywords: ["calories", "kcal", "protéines", "glucides", "lipides", "nutrition", "valeur", "énergétique"]
      patterns: ["\\d+\\s*kcal", "valeur.*nutrition", "pour\\s*100\\s*g"]

# OCR Configuration
ocr_settings:
  tesseract:
    languages: ["fra", "eng"]
    config: "--oem 3 --psm 6"
    dpi: 300
    
  easyocr:
    languages: ["fr", "en"]
    gpu: false
    batch_size: 1
    
  preprocessing:
    resize_factor: 2.0
    noise_reduction: true
    contrast_enhancement: true
    deskew: true
    
  postprocessing:
    spell_check: true
    language_filter: true
    confidence_threshold: 0.6

# Content Parsing Rules
content_parsing:
  pizza_extraction:
    name_patterns:
      - "pizza\\s+([\\w\\s]+?)(?=\\s*[€\\d]|$)"
      - "^([A-Z][\\w\\s]+?)\\s*[-–]"
    
    price_patterns:
      - "([\\d]+[.,][\\d]{2})\\s*€"
      - "€\\s*([\\d]+[.,][\\d]{2})"
    
    ingredient_patterns:
      - "ingrédients?\\s*:?\\s*([^\\n]+)"
      - "composition\\s*:?\\s*([^\\n]+)"

  allergen_extraction:
    table_detection:
      min_columns: 3
      max_columns: 15
      header_keywords: ["pizza", "gluten", "lactose", "œuf", "arachide"]
    
    presence_indicators: ["X", "✓", "●", "•", "oui", "yes", "présent"]
    absence_indicators: ["", "-", "non", "no", "absent"]

  recipe_extraction:
    ingredient_section:
      start_keywords: ["ingrédients", "ingredients"]
      end_keywords: ["préparation", "instructions", "étapes"]
    
    instruction_section:
      start_keywords: ["préparation", "instructions", "étapes"]
      numbered_steps: true

# Chunking Strategy
chunking:
  strategies:
    semantic:
      chunk_size: 1000
      chunk_overlap: 200
      separators: ["\n\n", "\n", ".", "!", "?"]
      
    pizza_based:
      delimiter_patterns:
        - "^pizza\\s+\\w+"
        - "^\\d+\\.\\s*\\w+"
      include_context: true
      
    table_based:
      preserve_structure: true
      include_headers: true
      max_rows_per_chunk: 10

  metadata_enrichment:
    page_number: true
    document_type: true
    extraction_method: true
    confidence_score: true
    language: true
    pizza_name: true  # When identifiable
    allergen_info: true  # When present

# Validation Rules
validation:
  required_fields:
    pizza_menu:
      - "pizza_name"
      - "price_or_description"
      
    allergen_table:
      - "pizza_names"
      - "allergen_columns"
      
    recipe:
      - "title"
      - "ingredients"

  safety_checks:
    allergen_consistency:
      cross_reference: true
      flag_contradictions: true
      
    completeness:
      min_pizzas_per_menu: 3
      min_allergens_per_table: 5

  quality_metrics:
    text_extraction:
      min_words_per_page: 50
      max_extraction_errors: 3
      
    structure_preservation:
      table_integrity: 0.9
      layout_accuracy: 0.8

# Post-processing
post_processing:
  text_cleaning:
    remove_duplicates: true
    normalize_whitespace: true
    fix_encoding_issues: true
    
  language_processing:
    detect_language: true
    normalize_text: true
    extract_entities: ["pizza_names", "ingredients", "allergens"]
    
  data_enrichment:
    add_timestamps: true
    add_source_info: true
    add_processing_metadata: true

# Error Handling
error_handling:
  extraction_failures:
    retry_count: 3
    fallback_methods: ["ocr", "manual_review"]
    
  validation_failures:
    log_issues: true
    flag_for_review: true
    continue_processing: false  # For safety-critical content
    
  quality_failures:
    min_acceptable_score: 0.7
    escalate_threshold: 0.5
    human_review_required: true

# Logging
logging:
  level: "INFO"
  log_extractions: true
  log_validations: true
  log_errors: true
  
  output_files:
    extraction_log: "logs/extraction.log"
    validation_log: "logs/validation.log"
    error_log: "logs/errors.log"